create database Store_Fusion;
select*from Store_Fusion.orders;
-- 1.Create Tables Based on ERD
create table Store_fusion.brands(
Brand_id int,
Brand_name varchar(100));
create table Store_fusion.categories(
Category_id int,
Category_name varchar(100));
create table Store_fusion.customers(
Customer_id int,
First_name varchar(100),
Last_name varchar(100),
Phone varchar(100),
Email varchar(100),
Street varchar(100),
City varchar(100),
State varchar(100),
Zip_code int);
create table Store_fusion.order_items(
Order_id int,
Item_id int,
Product_id int,
Quantity int,
List_price float,
Discount float,
Total_price float);
create table Store_fusion.ordrs(
Order_id int,
Customer_id int,
Order_status int,
Order_date date,
Required_date date,
Shipped_date date,
Store_id int,
Staff_id int,
Order_Progress varchar(100));
create table Store_fusion.products(
Product_id int,
Product_name varchar(100),
Brand_id int,
Category_id int,
Model_year int,
List_price float);
create table Store_fusion.staffs(
Staff_id int,
First_name varchar(100),
Last_name varchar(100),
Email varchar(100),
Phone varchar(100),
Active int,
Store_id int,
Manager_id varchar(100));
create table Store_fusion.stocks(
Store_id int,
Product_id int,
Quantity int );
create table Store_fusion.stores(
Store_id int,
Store_name varchar(100),
Phone varchar(100),
Email varchar(100),
Street varchar(100),
City varchar(100),
State varchar(100),
Zip_Code int);

-- 2. Import CSVs into SQL
-- Imported
-- 3.Inner Join for Order Details
-- Join orders,order_items and products to display detailed line items.
select o.order_id as order_id,o.customer_id as customer_id,p.product_id as product_id,p.category_id as customer_id,
oi.order_id as order_id,oi.product_id as product_id from store_fusion.orders as o
join store_fusion.order_items as oi
on o.order_id=oi.order_id 
join store_fusion.products as p
on p.Product_id=oi.Product_id;


-- 4.Total Sales by Store
-- Write a query to group sales(total_price) by each store_id.
select o.Store_id as Store_id,sum(oi.Total_price) as Total_price from store_fusion.orders as o
join store_fusion.order_items as oi 
on o.order_id=oi.order_id
group by Store_id;
-- 5.Top Selling Products
-- Use ORDER BY and LIMIT to get the top 5 most sold products by quantity.
select sum(oi.Quantity) as Total_Quantity,p.Product_id as Product_id from store_fusion.order_items as oi
join store_fusion.products as p
on p.Product_id=oi.Product_id
group by Product_id
order by sum(oi.Quantity) desc limit 5;


 -- 6. Customer Purchase Summary 
 -- For each customer, return total orders placed, total items purchased, and total revenue.
 select distinct Customer_id as Customer_id,count(Distinct(oi.Order_id))as Total_orders,sum(oi.Quantity) as Items_purchased ,sum(oi.Total_price) as Total_revenue from store_fusion.orders as o
 join store_fusion.order_items as oi
 on o.Order_id=oi.Order_id
 group by Customer_id;
 
 
 -- 7. Segment Customers by Total Spend 
 -- Write a query to classify customers into spending brackets (e.g., low, medium, high). 
select o.Customer_id,sum(oi.Total_price) as spending_amount,
case
when sum(oi.Total_price)<=10000 then "low spending"
when sum(oi.Total_price)<=35000 then "medium spening"
else "high spending"
end as Status
  from store_fusion.orders as o
join store_fusion.order_items as oi
on o.Order_id=oi.Order_id
group by Customer_id;
-- 8. Staff Performance Analysis 
 -- Analyze total revenue generated by each staff member based on their handled orders.
 select distinct o.Staff_id,sum(oi.Total_price) as Total_revenue from store_fusion.order_items as oi
 join store_fusion.orders as o
 on o.Order_id=oi.Order_id
 join store_fusion.staffs as st
 on st.Staff_id=o.Staff_id
 group by Staff_id;
 
-- 9. Stock Alert Query 
-- Write a query to list products where stock quantity < 10 in any store.
select p.Product_name as product_name,stor.Store_name as Store_name,sum(st.Quantity) as Quantity from store_fusion.stocks as st
join store_fusion.stores as stor
on stor.Store_id=st.Store_id
join store_fusion.products as p
on p.Product_id=st.Product_id
group by product_name,Store_name
having sum(st.Quantity)<10; 


-- 10. Create Final Segmentation Table 
 -- Create a table customer_segments that will be populated from Python ML results later.
  create table customer_segments(
 customer_ID int primary key,
 recency int,
 frequency int,
 monetary double,
 segment_label text);
 select*from store_fusion.customer_segments;
 
 
 
 
 
 
 
 
 
   


 


 
 

 
 
 




 
 




